const jan = ['1. What is your number one goal this year?','2. What are you most grateful for?','3. Are you content?','4. What is your best memory of last year?','5. What was the last major accomplishment you had?','6. What possession could you not live without?','7. Can people change?','8. What is the last “good” thing you ate?','9. What is your current favorite snack?','10. What made you smile today?','11. What’s your favorite accessory?','12. What is making you mad?','13. What did you have for dinner today?','14. What did you get done?','15. Who last called you on the phone?','16. Who are you in love with?','17. What are you grateful for?','18. The best part of today was ______________ .','19. My current favorite website is _________________.','20. What was the hardest thing you’re dealing with?','21. Today I wish I had more _________________.','22. Tomorrow will be better because ___________________.','23. What made today unusual?','24. What are you looking for from life?','25. What is your favorite thing to drink?','26. Today the temperature was ___________________.','27. How much did you spend at the grocery store the last time you went?','28. Tomorrow I will _________________________.','29. What was your last major purchase?','30. My house is a home because _______________________.','31. Who is the last person to tell you they loved you?'];
const feb = ['1. What is your favorite piece of art you own?','2. The most expensive bill I paid last month was ________.','3. What’s the last thing you apologized for?','4. My favorite color is ______________.','5. On a scale of 1-10 how is your health?','6. If you could do today over, would you change anything?','7. Name a person you wish you didn’t have to deal with today.','8. What is the largest TV screen in your house?','9. What time did you go to bed last night?','10. What did you buy today?','11. I wish I had ____________.','12. How many photos did you take today?','13. What book are you reading right now?','14. How many hours of sleep did you get last night?','15. Last thing you wanted but didn’t get.','16. What mood were you in today?','17. What was the last new thing you tried?','18. My biggest hope is _____________.','19. What has challenged your morals?','20. What kind of car are you driving?','21. List your pets.','22. What are three things you need to buy?','23. Today I felt really secure knowing __________________.','24. Whose life did you make a difference in today?','25. What is your super power?','26. What is annoying you?','27. What would have made today perfect?','28. What stresses you?','29. What did you do to take advantage of this extra day this year? '];
const mar = ['1. The funniest thing you heard today.','2. If you could have a new talent what would you want?','3. Who is your best friend but not your spouse?','4. What do you wish you had left unsaid?','5. What was the first thing you ate or drank today?','6. Are you saving or spending?','7. On a scale of 1-10 how clean is your house? (10 being the cleanest)','8. What is the last song you listened to?','9. What relaxes you?','10. What is the most valuable thing you own?','11. What did you find inspiring today?','12. Are you happy?','13. How much “me” time did you take today?','14. List three things you have faith in.','15. Who is the last person you said “I love you” to?','16. Did you seize any opportunities?','17. Where did you go today?','18. What advice were you given?','19. Today was ________________________.','20. What are you glad you did today?','21. When was your last vacation? Where did you go?','22. The greatest wisdom comes from _____________________.','23. Who is your hero?','24. Why?','25. If you could have read one person’s mind today, who would you choose?','26. What was the easiest thing about today?','27. Did you thank anyone today?','28. Did you work hard today?','29. What was in your post office box today?','30. Today was a complete ______________________.','31. What are you seeking? '];
const apr = ['1. Did you make someone laugh today? Was it intentional?','2. What makes you sad?','3. Was today typical? Why/Why not?','4. Who do you trust the most?','5. What’s your next major deadline? What is it for?','6. What did you have for breakfast today?','7. Do you have any regrets today?','8. How did you add art to your life today?','9. ______________ makes me happy.','10. When is the last time you danced?','11. List the people you live with.','12. What fears did you have today?','13. What did you forget?','14. What is your favorite TV show?','15. I have faith that _________________.','16. Who is the last person you kissed?','17. What did you wear today?','18. What is testing you?','19. What’s the oldest thing you’re wearing today?','20. List 5 things you should have done today.','21. Where did you spend the most time today?','22. Share a favorite quote.','23. Who did you worry about today?','24. Were you creative today? How?','25. What is the next major purchase you need to make?','26. What is the last thing that made you cry?','27. Today was tough because _________________.','28. Who are you jealous of?','29. Where do you want to go next?','30. What did you read today?'];
const may = ['1. Who was kind to you today?','2. Who is the last person you spoke with?','3. What makes you feel alive?','4. The store I frequent the most is _________________________.','5. How did you relax today?','6. Describe your favorite pair of shoes you own now.','7. What rule had the most impact on your day?','8. How many pairs of shoes do you own?','9. Today I lost __________________.','10. I really wish ___________ hadn’t been invented.','11. What’s the most expensive thing you own that you can carry?','12. How much money is in your wallet right now?','13. Why was today unique?','14. What did you leave undone today?','15. Today the weather was _________________________.','16. What was in your email today?','17. What do you wish you had said today?','18. What was the biggest decision you made today?','19. What are you waiting for?','20. What is the prevailing truth about your day.','21. What is the last thing you settled for?','22. Describe your day in a six word sentence.','23. What was the last thing that hurt you?','24. Did you use your time wisely today?','25. Did you have a dream last night? Describe it.','26. Where do you wish you were?','27. What music did you hear today?','28. What did you have the most fun doing today?','29. What do you love most about what you get to do every day?','30. What hobbies do you have?','31. What was the lowest point of your day?'];
const june = ['1. List the credit cards in your wallet.','2. How close to perfect was today?','3. When did you last sing out loud?','4. What was the last gathering you attended?','5. Did anything make you sad today?','6. Share a secret thought.','7. List 5 things you wish you invented.','8. What’s the last recipe you prepared?','9. Who is your most reliable friend?','10. What made you lose track of time today?','11. What are you confident about?','12. How did you do it?','13. What is the last purchase you made?','14. Did you show someone appreciation today?','15. How many push-ups can you do?','16. What are you looking forward to?','17. What is your favorite dish to prepare?','18. There is no such thing as too much _____________________________.','19. What is the most important thing you were told today?','20. What was the last thing you thought about today?','21. What is the last book you read?','22. What matters today?','23. What project are you working on?','24. Without looking at the previous years’ entry first, sign your name.','25. What is your most prized possession?','26. Were you ‘good’ or ‘bad’ today?','27. What is the smartest thing you did today?','28. What was in your mailbox today?','29. Today I was so ________________.','30. The last thing I bought myself was __________________.'];
const july = ['1. Were you alone today?','2. Who was the last person you saw today?','3. What do you need to let go of?','4. What movie are you looking forward to?','5. I just can’t ____________________.','6. Who did you text today?','7. Have you played the lottery?','8. A funny thing happened on the way to _____________________.','9. Name one thing you should toss right now, but just can’t.','10. What recently happened that made you proud of yourself?','11. Who did you see the most today?','12. Who inspires you?','13. How much is gasoline per gallon?','14. What was your horoscope today? Was it accurate?','15. What are you most afraid of?','16. What’s the biggest thing you have going on?','17. What did you accomplish today?','18. Did you act your age today?','19. How busy was your day today?','20. What was the hurry?','21. What is your address?','22. What do you wish there was less of in the world?','23. What is stopping you?','24. What were your chores today?','25. What was the last thing that made you laugh out loud?','26. Who did you eat dinner with?','27. How did you make a difference in the world today?','28. What is one thing you take with you everywhere?','29. The last gift I’ve given was ________________.','30. What motivated you today?','31. Who is your craziest friend?'];
const aug = ['1. What did you have for lunch today?','2. What did you let go of?','3. What is the one thing you want to accomplish tomorrow?','4. What was the last gift you gave?','5. The last time I exercised ____________________.','6. What did you create today?','7. What memories did you think about today?','8. What is the last risk you took?','9. What made you compromise?','10. Who do you look up to?','11. On a scale of 1-10 my day was a __________.','12. What did the last text message you received say?','13. Do you owe anyone money?','14. What is your own favorite physical feature?','15. What was the worst thing you ate today?','16. I hope no one was looking when I _______________.','17. How many miles did you drive/ride today?','18. Who was the first person you saw today?','19. What’s your biggest phobia?','20. What was your first full thought this morning?','21. How full is your fridge?','22. What was the last healthy thing you did for yourself?','23. What did you have to wait for today?','24. What did you win?','25. Who had the biggest influence on your day?','26. What can you learn from today?','27. What was the highest point of your day today?','28. Did you pay it forward?','29. What would you like to learn more about?','30. What new TV show do you refuse to watch?','31. How much is a gallon of milk?'];
const sept = ['1. What decision do you wish you didn’t have to make?','2. What are you questioning?','3. What was the most recent thing you learned?','4. Where would you like to go?','5. The last doctor’s appointment you made was because ___________.','6. Name 3 things you should have done today.','7. What is the last thing you felt guilty about?','8. My life would be easier if __________________.','9. Does anyone owe you money?','10. When is the last time you intentionally ‘wasted’ a day?','11. What is your favorite gadget?','12. The computer I use the most is _______________________.','13. How did you spend your free time today?','14. Were you stressed today? Why?','15. What was the last thing you said to another person?','16. Who threw the last party you went to?','17. What went perfectly about your day?','18. How old do you feel?','19. OMG! __________________.','20. What pressure did you feel today?','21. The last gift I’ve received was ________________.','22. If you could change today would you?','23. I believe ___________________.','24. What do you wish you could have skipped today?','25. Were you in control of your day?','26. What made today worthwhile?','27. Were you a good listener today?','28. I never ______________________.','29. Have you broken the law? How so?','30. Were you bored today? '];
const oct = ['1. Who is the last person you spent quality time with?','2. Who did you hug today?','3. Describe your day in one word.','4. How are you?','5. Did you do more talking or listening today?','6. How much is a gallon of gas?','7. What was the last stupid thing you did?','8. What’s the next book you are going to read?','9. What was the mistake?','10. What was the last gift you gave?','11. What is your mission?','12. If others described how you acted today in one word, it would be _________.','13. What is your current bank balance?','14. Describe the last piece of furniture you purchased.','15. What time did you wake up this morning?','16. Describe the last time you were embarrassed.','17. How did you improve yourself today?','18. How much time did you spend outside today?','19. In one year from today, what word do you hope best describes your life.','20. Who in your life is crazy talented? What is their talent?','21. What do you wish there was more of in the world?','22. My favorite sound is _________________ .','23. What impact do you hope to have on the world?','24. If you made laws, what one would you make today?','25. Describe your last life-changing moment.','26. What opportunity are you waiting for?','27. How many emails did you have today?','28. What is the last movie you saw?','29. Are you settling for something?','30. What is standing in your way?','31. What was the happiest headline in the news today?'];
const nov = ['1. What decision are you glad you made?','2. Share some good advice.','3. What occupied your mind today?','4. What was the best conversation you had today?','5. Do you love your job?','6. If you could get rid of one of your habits, what would it be?','7. List 5 things you wish you had with you today.','8. What are the achievements you are most proud of?','9. What gadgets did you use today?','10. What shocked you?','11. What was the last lie you told?','12. What is your favorite cuisine?','13. What do you have too much of?','14. What do you want to tell yourself in one year?','15. What is your greatest strength?','16. Other than your clothes, what was with you the majority of the day?','17. What’s your guilty pleasure?','18. What is bothering you?','19. What inspires you?','20. What impression did you make on others today?','21. What did you give up on today?','22. How did you play today?','23. How do you know?','24. Name the last three things you used today.','25. What sound do you hate hearing?','26. Do you feel appreciated?','27. My body is ______________________.','28. Today I had too much ________________.','29. What worries you?','30. What did you get to do today?'];
const dec = ['1. Who is your best friend?','2. I really wish _________________.','3. Who is the first person you saw today?','4. What memory do you want to keep from today?','5. How much money is in your wallet?','6. What makes you sweat?','7. What do you wish your job was?','8. What relationship did you nurture today?','9. What are you passionate about?','10. I realize tomorrow __________________.','11. Are you holding a grudge?','12. What was weird about your day?','13. How much of your day did you spend completely alone?','14. How are you expanding your mind?','15. What word are you using too much lately?','16. How was your day today?','17. What was the first thing you saw when you woke up this morning?','18. What are three things you need to do tomorrow?','19. What is the last place you visited online?','20. Today I chose to ________________.','21. Were you a positive or negative person today?','22. Who is the strongest person you know?','23. Who do you wish had been a part of your day?','24. What is one thing you were told today that you don’t want to forget?','25. What was your weakness today?','26. The music genre I listen to the most is ________________.','27. How much did you eat today?','28. What’s worth fighting for?','29. Today I felt ___________________.','30. Did you smile or frown more today?','31. What improvements are you making?'];



const months = [jan, feb, mar, apr, may, june, july, aug, sept, oct, nov, dec];

let prompts = []
months.forEach(month => {
    month.forEach(p => {
        prompts.push(`\n('${p.split('. ')[1]}', FALSE)`)
    })
})

// console.log(prompts)

const fs = require('fs') 

fs.writeFile('prompts.txt', prompts, (err) => { 
      
    // In case of a error throw err. 
    if (err) throw err; 
})